[general]
# Whether the hook should export class medals (dans) and emblems.
export_class = true

# Whether FAILED lamps should override FULL COMBO and ALL JUSTICE.
# Not recommended, but it's an option.
fail_over_lamp = false

# Timeout for web requests, in milliseconds. If your network connection
# to Tachi is unstable, you might want to bump this up.
timeout = 3000

# Whether the hook should update itself when a new update is found.
auto_update = true

# The directory/folder to store failed imports due to network
# connectivity issues. It will not save any imports rejected
# by Tachi for other reasons.
failed_import_dir = "failed_saekawa_imports"

[cards]
# Tachi API keys go here. You can set a default API key for all
# cards using the `default` key:
#    default = "example-api-key"
# You can also set the API key that will be used for a specific access code
# (useful for shared setups):
#    "00001111222233334444" = "example-api-key-1"
#    "55556666777788889999" = "example-api-key-2"
# The `default` key can also be removed, discarding any scores
# that do not come from the list of access codes configured.

default = "your-api-key"

[tachi]
# The base URL of the Tachi instance to submit scores to.
base_url = "https://kamai.tachi.ac/"
