[general]
# Set to 'false' to disable the hook
enable = true
# Whether the hook should export your class medals and emblems or not.
export_class = true
# Timeout for web requests, in milliseconds
timeout = 3000

[cards]
# Access codes that should be whitelisted
# If this is empty, all cards will be whitelisted
# There should be no whitespace between the digits
# example: whitelist = ["00001111222233334444"]
whitelist = []

[tachi]
# Tachi instance base URL
base_url = 'https://kamaitachi.xyz/'
# Tachi status endpoint
status = '/api/v1/status'
# Tachi score import endpoint
import = '/ir/direct-manual/import'
# Your Tachi API key
api_key = 'your-key-here'